backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo here
public_folder: "/img"

collections:
  - name: "plants"
    label: "Plants"
    folder: "src/plants"
    create: true
    slug: "{{slug}}"
    fields:
      - {slug: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Planted Date", name: "plantedDate", widget: "date"}
      - {label: "Days to Harvest", name: "daysToHarvest", widget: "number"}
      - {label: "Harvest Window", name: "harvestWindow", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
